name: homehub
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.1.1
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  mobile_scanner: ^3.2.0
  riverpod_annotation: ^2.0.1
  streaming_shared_preferences: ^2.0.0
  web_socket_channel: ^2.4.0
  wakelock: ^0.4.0
  weather_icons: ^3.0.0
  syncfusion_flutter_charts: ^21.1.41
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  custom_lint:
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
